# Generated by Django 3.1 on 2020-08-31 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afringa', '0002_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='audiofile',
            field=models.FileField(null=True, upload_to='audio/', verbose_name=''),
        ),
    ]
